export const consultCards = [
    {
      id: 1,
      image: require("../../../../assets/consultas/cuidado-del-cabello.jpg"),
      title: "Cuidado del cabello",
      description:
        "En Rogans entendemos lo desafiante que puede ser lidiar con la pérdida de cabello y sus efectos en la autoestima y la confianza. Te ofrecemos un enfoque integral y experto para abordar la alopecia y ayudarlo a recuperar su cabello y su confianza.",
      duracion_cita: "30 minutos",
      precio_cita: "80000",
    },
    {
      id: 2,
      image: require("../../../../assets/consultas/cuidado-de-la-piel.jpg"), // foto pendiente
      title: "Cuidado de la piel",
      description:
        "Reconocemos la importancia de mantener una piel saludable, radiante y rejuvenecida. Te brindamos soluciones personalizadas y tratamientos cosméticos de vanguardia para ayudarte a lograr tu apariencia ideal.",
      duracion_cita: "30 minutos",
      precio_cita: "50000",
    },
    {
      id: 3,
      image: require("../../../../assets/consultas/rendimiento-sexual.jpg"),
      title: "Rendimiento Sexual",
      description:
        "Comprendemos que la salud sexual es una parte fundamental de la calidad de vida.  Te brindamos un espacio seguro y confidencial donde puedes abordar tus inquietudes y mejorar tu vida sexual.",
      duracion_cita: "30 minutos",
      precio_cita: "100000",
    },
    {
      id: 4,
      image: require("../../../../assets/consultas/salud-mental.jpg"),
      title: "Salud Mental",
      description:
        "Tu salud mental es nuestra prioridad, y estamos comprometidos a trabajar contigo para que puedas vivir una vida más plena y equilibrada.",
      duracion_cita: "30 minutos",
      precio_cita: "80000",
      category: 'Capilar',
    },
    {
      id: 5,
      image: require("../../../../assets/consultas/consulta-medica-general.jpg"),
      title: "Medicina General",
      description:
        "Nos enorgullece ofrecer atención médica integral para cuidar de tu salud en general. Con médicos altamente calificados que se dedican  a proporcionar atención médica personalizada y completa para toda tu familia.",
      duracion_cita: "20 minutos",
      precio_cita: "50000",
      category: 'Capilar',
    },
    {
      id: 6,
      image: require("../../../../assets/consultas/estetica-dental.jpg"),
      title: "Estética dental ",
      description:
        "Te ayudamos a lograr la sonrisa perfecta que siempre has deseado. Nuestro equipo de especialistas en odontología estética se dedica a transformar sonrisas y a mejorar la confianza de nuestros pacientes.",
      duracion_cita: "30 minutos",
      precio_cita: "80000",
      category: 'Capilar',
    },
    {
      id: 7,
      image: require("../../../../assets/consultas/nutricion.jpg"),
      title: "Nutrición",
      description:
        "Contamos con expertos en nutrición quienes te diseñar planes personalizados que se ajusten a tu estilo de vida y necesidades individuales como:  Perder peso, aumentar tu energía o mejorar tus hábitos alimenticios.",
      duracion_cita: "45 minutos",
      precio_cita: "80000",
      category: 'Capilar',
    },
  ];

  export const procedureCards = [
    { 
      id: 1,
      departamento: 'Capilar',
      title: 'Trasplante capilar', 
      image: require('../../../../assets/procedimientos/capilar/implante-capilar.jpg'), 
      description: 'Un trasplante capilar es un procedimiento quirúrgico en el que se toman folículos pilosos de una parte del cuerpo para ser trasplantadas a una zona que ha experimentado pérdida de cabello. Este procedimiento se utiliza comúnmente para tratar la calvicie o la alopecia.',
      duracion_cita: "20 minutos",
      tipo_cita: 'presencial',
      precio_cita: '100000',
    },
    { 
      id: 2,
      departamento: 'Capilar',
      title: 'Mesoterapia capilar ',  
      image: require('../../../../assets/procedimientos/capilar/mesoterapia-capilar.jpg'), 
      description: 'Es un tratamiento médico utilizado para combatir la pérdida de cabello y estimular el crecimiento capilar. Consiste en la administración de pequeñas inyecciones de sustancias nutritivas, vitaminas, minerales y otros ingredientes beneficiosos directamente en el cuero cabelludo.',
      duracion_cita: "20 minutos",
      tipo_cita: 'presencial',
      precio_cita: '80000', 
    },
    { 
      id: 3,
      departamento: 'Capilar',
      title: 'Fototerapia Capilar', 
      image: require('../../../../assets/procedimientos/capilar/fototerapia-capiar.jpg'), 
      description: 'La fototerapia capilar, también conocida como terapia con luz para el cabello, es un tratamiento no invasivo que utiliza luz para estimular el crecimiento del cabello y mejorar la salud del cuero cabelludo.',
      duracion_cita: "20 minutos",
      tipo_cita: 'presencial',
      precio_cita: '90000', 
    },
    { 
      id: 4,
      departamento: 'Facial',
      title: 'Toxina Botulínica', 
      image: require('../../../../assets/procedimientos/facial/botox.jpg'), 
      description: 'Es un procedimiento estético  que se utiliza  principalmente para suavizar las arrugas faciales que son causadas por la actividad repetitiva de los músculos faciales.',
      duracion_cita: "20 minutos",
      tipo_cita: 'presencial',
      precio_cita: 'Gratis', 
    },
    { 
      id: 5,
      departamento: 'Facial',
      title: 'Ácido Hialuronico', 
      image: require('../../../../assets/procedimientos/facial/Ácido-hialurónico.jpg'), 
      description: 'En procedimientos estéticos para mejorar la apariencia de la piel y restaurar el volumen facial.',
      duracion_cita: "20 minutos",
      tipo_cita: 'presencial',
      precio_cita: 'Gratis',
    },
    { 
      id: 6,
      departamento: 'Corporal',
      title: 'Cirugía Plastica', 
      image: require('../../../../assets/procedimientos/corporal/cirugia-plastica.jpg'), 
      description: 'La cirugía plástica facial se enfoca en mejorar la apariencia y la función de la cara y el cuello. Incluyendo la corrección de defectos congénitos, traumatismos, enfermedades, procesos de envejecimiento o  para mejorar la apariencia estética.',
      duracion_cita: "20 minutos",
      tipo_cita: 'presencial',
      precio_cita: 'Gratis', 
    },
    { 
      id: 7,
      departamento: 'Corporal',
      title: 'Hidrolipoclasia', 
      image: require('../../../../assets/procedimientos/corporal/Hidrolipoclapsia.jpg'), 
      description: 'Es un procedimiento médico estético que se utiliza para eliminar depósitos de grasa localizados en el cuerpo mediante la inyección en el área tratada. También es conocida como "liposucción sin cirugía"',
      duracion_cita: "20 minutos",
      tipo_cita: 'presencial',
      precio_cita: '80000', 
    },
    { 
      id: 8,
      departamento: 'Corporal',
      title: 'Sueroterapia', 
      image: require('../../../../assets/procedimientos/corporal/Suero-terapia.jpg'), 
      description: 'También conocida como terapia de infusión intravenosa ,es un procedimiento médico en el cual se administra una mezcla de líquidos y nutrientes directamente en el torrente sanguíneo a través de una vía intravenosa.',
      duracion_cita: "30 minutos",
      tipo_cita: 'presencial',
      precio_cita: '80000', 
    },
    { 
      id: 9,
      departamento: 'Corporal',
      title: 'ADN', 
      image: require('../../../../assets/procedimientos/ADN.jpg'), 
      description: 'Contamos con Kits que pueden ayudarte a descubrir información valiosa sobre tus antecedentes familiares, predisposiciones genéticas y mucho más.',
      duracion_cita: "20 minutos",
      tipo_cita: 'presencial-virtual',
      precio_cita: '80000', 
    },
    { 
      id: 10,
      departamento: 'Facial',
      title: 'Limpieza Facial', 
      image: require('../../../../assets/procedimientos/Limpieza-facial.jpg'), 
      description: 'Es un procedimiento básico de cuidado de la piel que tiene como objetivo eliminar la suciedad, el exceso de grasa, las impurezas y las células muertas de la superficie de la piel.',
      duracion_cita: "20 minutos",
      tipo_cita: 'presencial',
      precio_cita: 'Gratis', 
    },
    { 
      id: 11,
      departamento: 'Facial',
      title: 'Harmonyca', 
      image: require('../../../../assets/procedimientos/Harmonyca.jpg'), 
      description: 'Es un tratamiento que combina la bio estimulación de la hidroxiapatita de calcio y ácido hialurónico para definición del contorno mandibular.',
      duracion_cita: "30 minutos",
      tipo_cita: 'presencial',
      precio_cita: 'Gratis', 
    },
    { 
      id: 12,
      departamento: 'Facial',
      title: 'Radiesse', 
      image: require('../../../../assets/procedimientos/Radiesse.jpg'), 
      description: 'Es un relleno dérmico a base de calcio hidroxiapatita (CaHA) que se utiliza para tratar temas de envejecimiento facial y la pérdida de volumen.',
      duracion_cita: "30 minutos",
      tipo_cita: 'presencial',
      precio_cita: 'Gratis', 
    },
    { 
      id: 13,
      departamento: 'Facial',
      title: 'Hibridación dinámica', 
      image: require('../../../../assets/procedimientos/hibridacion.jpg'), 
      description: 'Es procedimiento que combina diferentes tratamientos y técnicas en medicina estética para abordar múltiples preocupaciones de manera simultánea.',
      duracion_cita: "60 minutos",
      tipo_cita: 'presencial',
      precio_cita: 'Gratis', 
    },
    { 
      id: 14,
      departamento: 'Facial',
      title: 'Plasma Facial (PRP)', 
      image: require('../../../../assets/procedimientos/Plasma.jpg'), 
      description: 'El PRP se utiliza para mejorar la textura y la apariencia de la piel, reducir líneas finas y arrugas, y promover un aspecto más juvenil.',
      duracion_cita: "60 minutos",
      tipo_cita: 'presencial',
      precio_cita: 'Gratis', 
    },
    { 
      id: 15,
      departamento: 'Facial',
      title: 'NCTF', 
      image: require('../../../../assets/procedimientos/nctf-solo-rostro.jpg'), 
      description: 'NCTF es una solución polirevitalizante que contiene más de 50 ingredientes activos, incluye: Vitaminas, aminoácidos, minerales y coenzimas que ayudan a optimizar las funciones celulares de la piel.',
      duracion_cita: "30 minutos",
      tipo_cita: 'presencial',
      precio_cita: 'Gratis', 
    },
    { 
      id: 16,
      departamento: 'Facial',
      title: 'Cosmelan', 
      image: require('../../../../assets/procedimientos/Cosmelan.jpg'), 
      description: 'Es un tratamiento despigmentante de la piel utilizado para tratar y reducir la hiperpigmentación, las manchas oscuras y las irregularidades en la pigmentación de la piel.',
      duracion_cita: "60 minutos",
      tipo_cita: 'presencial',
      precio_cita: 'Gratis', 
    },
    { 
      id: 17,
      departamento: 'Facial',
      title: 'Dermapen', 
      image: require('../../../../assets/procedimientos/Dermopen.jpg'), 
      description: 'Es tratamiento de microneedling o microagujas. Este procedimiento estético implica la aplicación de pequeñas agujas en la piel para estimular la producción de colágeno y promover la regeneración celular.',
      duracion_cita: "60 minutos",
      tipo_cita: 'presencial',
      precio_cita: 'Gratis', 
    },
    { 
      id: 18,
      departamento: 'Facial',
      title: 'Peeling Químico', 
      image: require('../../../../assets/procedimientos/pelling.jpg'), 
      description: 'Es un procedimiento que mejora el aspecto de las manchas en rostro, manos , disminuye la pigmentación oscura de los párpados.',
      duracion_cita: "30 minutos",
      tipo_cita: 'presencial',
      precio_cita: 'Gratis', 
    },
    { 
      id: 19,
      departamento: 'Facial',
      title: 'Hidratación facial con mascarilla de CO2', 
      image: require('../../../../assets/procedimientos/facial.jpg'), 
      description: 'También conocida como mascarilla de burbujas de oxígeno, es un tratamiento que utiliza dióxido de carbono (CO2) para proporcionar hidratación, mejora la textura de la piel, estimula el colágeno.',
      duracion_cita: "30 minutos",
      tipo_cita: 'presencial',
      precio_cita: 'Gratis', 
    },
    { 
      id: 20,
      departamento: 'Facial',
      title: 'ProfHilo', 
      image: require('../../../../assets/procedimientos/ProfHilo.jpg'), 
      description: 'Es un tratamiento estético con ácido hialurónico para mejorar la calidad de la piel y proporcionar un efecto de rejuvenecimiento facial. Principalmente estimula la producción de colágeno y elastina.',
      duracion_cita: "30 minutos",
      tipo_cita: 'presencial',
      precio_cita: 'Gratis', 
    },
  ];