// constants/countries.js
export const americanCountries = [
  { country: "Argentina", code: "+54", flag: "https://flagcdn.com/w320/ar.png" },
  { country: "Belize", code: "+501", flag: "https://flagcdn.com/w320/bz.png" },
  { country: "Bolivia", code: "+591", flag: "https://flagcdn.com/w320/bo.png" },
  { country: "Brazil", code: "+55", flag: "https://flagcdn.com/w320/br.png" },
  { country: "Canada", code: "+1", flag: "https://flagcdn.com/w320/ca.png" },
  { country: "Chile", code: "+56", flag: "https://flagcdn.com/w320/cl.png" },
  { country: "Colombia", code: "+57", flag: "https://flagcdn.com/w320/co.png" },
  { country: "Costa Rica", code: "+506", flag: "https://flagcdn.com/w320/cr.png" },
  { country: "Cuba", code: "+53", flag: "https://flagcdn.com/w320/cu.png" },
  { country: "Ecuador", code: "+593", flag: "https://flagcdn.com/w320/ec.png" },
  { country: "El Salvador", code: "+503", flag: "https://flagcdn.com/w320/sv.png" },
  { country: "Guatemala", code: "+502", flag: "https://flagcdn.com/w320/gt.png" },
  { country: "Haiti", code: "+509", flag: "https://flagcdn.com/w320/ht.png" },
  { country: "Honduras", code: "+504", flag: "https://flagcdn.com/w320/hn.png" },
  { country: "Jamaica", code: "+1-876", flag: "https://flagcdn.com/w320/jm.png" },
  { country: "Mexico", code: "+52", flag: "https://flagcdn.com/w320/mx.png" },
  { country: "Nicaragua", code: "+505", flag: "https://flagcdn.com/w320/ni.png" },
  { country: "Panama", code: "+507", flag: "https://flagcdn.com/w320/pa.png" },
  { country: "Paraguay", code: "+595", flag: "https://flagcdn.com/w320/py.png" },
  { country: "Peru", code: "+51", flag: "https://flagcdn.com/w320/pe.png" },
  { country: "Suriname", code: "+597", flag: "https://flagcdn.com/w320/sr.png" },
  { country: "United States", code: "+1", flag: "https://flagcdn.com/w320/us.png" },
  { country: "Uruguay", code: "+598", flag: "https://flagcdn.com/w320/uy.png" },
  { country: "Venezuela", code: "+58", flag: "https://flagcdn.com/w320/ve.png" },
];
