export const americanCountries = [
  { country: "Argentina", code: "+54" },
  { country: "Belize", code: "+501" },
  { country: "Bolivia", code: "+591" },
  { country: "Brazil", code: "+55" },
  { country: "Canada", code: "+1" },
  { country: "Chile", code: "+56" },
  { country: "Colombia", code: "+57" },
  { country: "Costa Rica", code: "+506" },
  { country: "Cuba", code: "+53" },
  { country: "Ecuador", code: "+593" },
  { country: "El Salvador", code: "+503" },
  { country: "Guatemala", code: "+502" },
  { country: "Haiti", code: "+509" },
  { country: "Honduras", code: "+504" },
  { country: "Jamaica", code: "+1-876" },
  { country: "Mexico", code: "+52" },
  { country: "Nicaragua", code: "+505" },
  { country: "Panama", code: "+507" },
  { country: "Paraguay", code: "+595" },
  { country: "Peru", code: "+51" },
  { country: "Suriname", code: "+597" },
  { country: "United States", code: "+1" },
  { country: "Uruguay", code: "+598" },
  { country: "Venezuela", code: "+58" },
];
